### ISSUE TITLE
چیزی به اسم subscription ID وجود ندارد

### ISSUE THREAD

**Issue by Hossein-Teimouri** [M4mmad/3xui-multi-protocol#7]
آخرین ورژن پنل sanaei رو نصب کردم اما فیلد subscription ID رو پیدا نمیکنم

![Screenshot_20240120-091217_Chrome](https://github.com/M4mmad/3xui-multi-protocol/assets/105169415/ac3f18d1-206f-4eed-8741-953be4fcdc0f)

**Comment by M4mmad** [comment]
اول از تنظیمات پنل فعالش کنید بعد همینجا نمایش داده میشه
